#apiVersion: v1
#kind: Namespace
#metadata:
#  name: env-b

#---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenantone-compute-quota
  namespace: tenantone
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: tenantone
spec:
  selector:
    app: app
  type: NodePort
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: tenantone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: CONTAINER_IMAGE
          imagePullPolicy: Always
          name: app
          resources:
            requests:
              cpu: 200m
              memory: 0.5Gi
            limits:
              cpu: 400m
              memory: 1Gi
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KEYDATA
              value: "ValueData"
      nodeSelector:
        nodegroup-type: frontend-workloads
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tenantone-ingress
  namespace: tenantone
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=14400
  labels:
    app: app
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: app
              servicePort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tenantoneapp
  namespace: tenantone
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
